#!/bin/bash
# hexciri:lib: makepkg tuning helper — writes per-PC build settings for AUR/makepkg.
# Sourced by install.sh (fresh installs) AND bin/hexciri-sync (existing machines,
# FIX POLICY). Idempotent + diff-minimal: rewrites the drop-in only on change.
# Needs root (writes /etc). Never touches the user's /etc/makepkg.conf.
#
#   hexciri_apply_makepkg_tuning   detect + (re)write /etc/makepkg.conf.d/
#
# Per-PC = this CPU's real tier (znver4/v4/v3/x86-64 via /lib/ld-linux-x86-64.so.2
# + vendor match, same rule bin/hexciri-cachyos uses) and real nproc. Official
# repo packages are unaffected (prebuilt); this only speeds up local/AUR builds.

hexciri_detect_cpu_tier() {
  local ld=/lib/ld-linux-x86-64.so.2
  local v3=false v4=false
  $ld --help 2>/dev/null | grep -q 'x86-64-v3 (supported,' && v3=true
  $ld --help 2>/dev/null | grep -q 'x86-64-v4 (supported,' && v4=true
  if $v4 && grep -q '^vendor_id\s*:\s*AuthenticAMD' /proc/cpuinfo; then
    echo "znver4"
  elif $v4; then
    echo "x86-64-v4"
  elif $v3; then
    echo "x86-64-v3"
  else
    echo "x86-64"
  fi
}

hexciri_apply_makepkg_tuning() {
  (( EUID == 0 )) || { echo "hexciri-makepkg: needs root (writes /etc/makepkg.conf.d)" >&2; return 1; }

  local tier jobs march body stamped
  tier="$(hexciri_detect_cpu_tier)"
  jobs="$(nproc 2>/dev/null || echo 1)"

  case "$tier" in
    znver4)    march="-march=znver4" ;;
    x86-64-v4) march="-march=x86-64-v4" ;;
    x86-64-v3) march="-march=x86-64-v3" ;;
    *)         march="" ;; # plain x86-64: keep the distro default
  esac

  body="# hexciri per-PC makepkg tuning (auto-written; CPU tier: $tier on $(getconf _NPROCESSORS_ONLN 2>/dev/null || echo $jobs) threads)
# AUR/local builds only — official repo packages are prebuilt and unaffected.
MAKEFLAGS=\"-j$jobs\"
COMPRESSZST=(zstd -q -c -T$jobs -19 -)
"
  [[ -n $march ]] && body+="CFLAGS=\"$march -O2 -pipe -fno-plt\"
CXXFLAGS=\"$march -O2 -pipe -fno-plt\"
"

  mkdir -p /etc/makepkg.conf.d
  stamped="# hexciri per-PC makepkg tuning (tier $tier, nproc $jobs) — regenerated by install/hexciri-sync"
  if [[ ! -f /etc/makepkg.conf.d/hexciri-tuning.conf ]] || \
     [[ "$(head -n1 /etc/makepkg.conf.d/hexciri-tuning.conf 2>/dev/null || true)" != "$stamped" ]]; then
    printf '%s\n%s' "$stamped" "$body" > /etc/makepkg.conf.d/hexciri-tuning.conf
    echo "hexciri: makepkg tuned for this machine ($tier, $jobs threads)"
  fi

  # The drop-in only works if makepkg actually LOADS it. This makepkg has no
  # `Include` keyword (grep /usr/bin/makepkg for it = 0), and /etc/makepkg.conf
  # sources nothing — so a conf.d file sits inert, exactly like fortran.conf /
  # rust.conf here. Make the load happen by appending a bash source block with a
  # marker (idempotent); runs after the distro defaults at EOF, so our values
  # win. Sourcing the whole glob also finally arms rust.conf/fortran.conf.
  marker='# hexciri: source /etc/makepkg.conf.d drop-ins (makepkg lacks Include support)'
  if ! grep -qF "$marker" /etc/makepkg.conf 2>/dev/null; then
    {
      echo
      echo "$marker"
      echo 'for _f in /etc/makepkg.conf.d/*.conf; do [[ -e $_f ]] && source "$_f"; done'
    } >> /etc/makepkg.conf
    echo "hexciri: /etc/makepkg.conf now sources /etc/makepkg.conf.d (drop-ins active)"
  fi
}