-- Keybinds — rendered from config/keybinds/intents.toml (single source of truth).
-- Included automatically via require("hypr.conf.keybinds") in hyprland.lua.
-- Regenerate with: hexciri-keybinds-render hyprland > config/hypr/conf/keybinds.lua
hl.bind("SUPER + 0", hl.dsp.focus({ workspace = "browser" }))
hl.bind("SUPER + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind("SUPER + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind("SUPER + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind("SUPER + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind("SUPER + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind("SUPER + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind("SUPER + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind("SUPER + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind("SUPER + 9", hl.dsp.focus({ workspace = 9 }))
hl.bind("SUPER + C", hl.dsp.exec_cmd("sh -c 'wtype -M ctrl -k c'"))
hl.bind("SUPER + D", hl.dsp.exec_cmd("noctalia msg panel-toggle launcher"))
hl.bind("SUPER + F", hl.dsp.window.fullscreen({ mode = "maximized", action = "toggle" }))
hl.bind("SUPER + H", hl.dsp.focus({ direction = 'l' }))
hl.bind("SUPER + I", hl.dsp.focus({ workspace = "e-1" }))
hl.bind("SUPER + J", hl.dsp.focus({ direction = 'd' }))
hl.bind("SUPER + K", hl.dsp.exec_cmd("hexciri-keybinds"))
hl.bind("SUPER + L", hl.dsp.focus({ direction = 'r' }))
hl.bind("SUPER + N", hl.dsp.exec_cmd("noctalia msg panel-toggle notifications"))
-- Mod+O → overview:toggle: no Lua sibling binding emitted
hl.bind("SUPER + P", hl.dsp.focus({ window = "floating" }))
hl.bind("SUPER + Q", hl.dsp.window.close())
hl.bind("SUPER + R", hl.dsp.window.resize())
hl.bind("SUPER + U", hl.dsp.focus({ workspace = "e+1" }))
hl.bind("SUPER + V", hl.dsp.exec_cmd("sh -c 'wtype -M ctrl -k v'"))
hl.bind("SUPER + X", hl.dsp.exec_cmd("sh -c 'wtype -M ctrl -k x'"))
hl.bind("SUPER + Up", hl.dsp.focus({ direction = 'u' }))
hl.bind("SUPER + Down", hl.dsp.focus({ direction = 'd' }))
hl.bind("SUPER + Left", hl.dsp.focus({ direction = 'l' }))
hl.bind("ALT + Print", hl.dsp.exec_cmd("hexciri-screenrecord"))
hl.bind("SUPER + comma", hl.dsp.exec_cmd("noctalia msg notification-clear-active"))
hl.bind("SUPER + Print", hl.dsp.exec_cmd("hexciri-compositor screenshot"))
hl.bind("SUPER + Right", hl.dsp.focus({ direction = 'r' }))
hl.bind("SUPER + space", hl.dsp.exec_cmd("hexciri-fuzzel"))
hl.bind("SUPER + grave", hl.dsp.exec_cmd("hexciri-agent"))
hl.bind("CTRL + Print", hl.dsp.exec_cmd("sh -c 'grim -g \"$(slurp)\" - | wl-copy'"))
hl.bind("SUPER + CTRL + F", hl.dsp.window.fullscreen({ action = "toggle" }))
hl.bind("SUPER + CTRL + H", hl.dsp.window.move({ direction = 'l' }))
hl.bind("SUPER + CTRL + J", hl.dsp.window.move({ direction = 'd' }))
hl.bind("SUPER + CTRL + K", hl.dsp.window.move({ direction = 'u' }))
hl.bind("SUPER + CTRL + L", hl.dsp.exec_cmd("hexciri-lock"))
hl.bind("SUPER + CTRL + M", hl.dsp.exec_cmd("hexciri-launch-or-focus-webapp messenger https://www.messenger.com"))
hl.bind("SUPER + CTRL + V", hl.dsp.exec_cmd("hexciri-clipboard"))
hl.bind("SUPER + Escape", hl.dsp.exec_cmd("hexciri-power"))
hl.bind("SUPER + Return", hl.dsp.exec_cmd("hexciri-terminal"))
hl.bind("SUPER + CTRL + Up", hl.dsp.window.move({ direction = 'u' }))
hl.bind("SUPER + SHIFT + 0", hl.dsp.window.move({ workspace = "browser", follow = false }))
hl.bind("SUPER + SHIFT + 1", hl.dsp.window.move({ workspace = 1, follow = true }))
hl.bind("SUPER + SHIFT + 2", hl.dsp.window.move({ workspace = 2, follow = true }))
hl.bind("SUPER + SHIFT + 3", hl.dsp.window.move({ workspace = 3, follow = true }))
hl.bind("SUPER + SHIFT + 4", hl.dsp.window.move({ workspace = 4, follow = true }))
hl.bind("SUPER + SHIFT + 5", hl.dsp.window.move({ workspace = 5, follow = true }))
hl.bind("SUPER + SHIFT + 6", hl.dsp.window.move({ workspace = 6, follow = true }))
hl.bind("SUPER + SHIFT + 7", hl.dsp.window.move({ workspace = 7, follow = true }))
hl.bind("SUPER + SHIFT + 8", hl.dsp.window.move({ workspace = 8, follow = true }))
hl.bind("SUPER + SHIFT + 9", hl.dsp.window.move({ workspace = 9, follow = true }))
hl.bind("SUPER + SHIFT + B", hl.dsp.exec_cmd("xdg-open https://"))
hl.bind("SUPER + SHIFT + E", hl.dsp.exec_cmd("zeditor"))
hl.bind("SUPER + SHIFT + F", hl.dsp.exec_cmd("~/.local/bin/strata"))
hl.bind("SUPER + SHIFT + P", hl.dsp.focus({ window = "tiled" }))
hl.bind("SUPER + SHIFT + R", hl.dsp.group.toggle())
hl.bind("XF86Launch5", hl.dsp.exec_cmd("hexciri-launch-or-focus-webapp gemini https://gemini.google.com/app"))
hl.bind("XF86Launch6", hl.dsp.exec_cmd("hexciri-launch-or-focus-webapp photopea https://photopea.com"))
hl.bind("SUPER + ALT + space", hl.dsp.exec_cmd("hexciri-menu"))
hl.bind("SUPER + CTRL + Down", hl.dsp.window.move({ direction = 'd' }))
hl.bind("SUPER + CTRL + Left", hl.dsp.window.move({ direction = 'l' }))
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"))
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"))
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"))
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"))
hl.bind("SUPER + CTRL + Right", hl.dsp.window.move({ direction = 'r' }))
hl.bind("SUPER + bracketleft", hl.dsp.window.swap({ direction = 'l' }))
hl.bind("SUPER + SHIFT + space", hl.dsp.window.float({ action = "toggle" }))
hl.bind("SUPER + bracketright", hl.dsp.window.swap({ direction = 'r' }))
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"))
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl set 5%+"))
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"))
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"))
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl set 5%-"))
