# See the pacman.conf(5) manpage for option and repository directives
# hexciri bleeding channel — normal Arch rolling release + edge pkgs (has linux-omarchy* BORE/MuQSS)

[options]
Color
ILoveCandy
VerbosePkgLists
HoldPkg = pacman glibc
Architecture = auto
CheckSpace
ParallelDownloads = 5
DownloadUser = alpm

SigLevel = Required DatabaseOptional
LocalFileSigLevel = Optional

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist

[omarchy]
Server = https://pkgs.omarchy.org/edge/$arch
